export const en = {
    nav: {
        overview: 'Business Overview',
        invoices: 'Order History',
        menu: 'Menu Management',
        hr: 'User Management',
        floorplan: 'Floor Plan',
        shift_report: 'Shift Report',
        reports: 'Sales Reports',
        orders: 'Orders',
        products: 'Products',
        users: 'Staff',
        home: 'Home',
        dashboard: 'Dashboard',
        product_qty: 'Product (Qty)',
        topping: 'Topping',
        history: 'History',
        history: 'History',
        language: 'Language',
        terms: 'Terms',
        sync_data: 'Sync Data',
        support: 'Support',
        settings: 'Settings',
        receipts: 'Receipts',
        payment_requests: 'Payment Requests',
        kitchen_notifs: 'Kitchen Notifications',
        help: 'Help',
        logout_processing: 'Logging out...'
    },
    app: {
        exit_title: 'Exit App',
        exit_confirm: 'Are you sure you want to exit?',
        exit_ok: 'Exit',
        exit_cancel: 'Cancel',
        admin_subtitle: 'Administrator Portal'
    },
    action: {
        checkout: 'Checkout',
        add_item: 'Add Item',
        edit: 'Edit',
        delete: 'Delete',
        sync: 'Sync Cloud',
        save: 'Save Changes',
        cancel: 'Cancel',
        confirm: 'Confirm',
        refresh: 'Refresh',
        export: 'Export CSV',
        import_csv: 'Import CSV',
        export_csv: 'Export CSV',
        add_new: 'Add New',
        update: 'Update'
    },
    status: {
        active: 'Active',
        empty: 'Available',
        paid: 'Completed',
        pending: 'Pending',
        cancelled: 'Cancelled',
        removed: 'Removed',
        draft: 'Draft',
        occupied: 'Occupied'
    },
    pos: {
        takeaway: 'Takeaway',
        placeholder_note: 'e.g., less sugar, no ice...',
        add_to_order: 'Add to Order',
        update_item: 'Update Item',
        qty: 'Qty'
    },
    cart: {
        empty_title: 'No items yet',
        empty_instruction_prefix: 'Please press',
        empty_instruction_suffix: 'button to add items',
        save_draft: 'Save Draft',
        item_note_title: 'Item Note',
        order_note_title: 'Order Note',
        enter_note_placeholder: 'Enter note...',
        confirm_delete_item_title: 'Confirm Delete',
        confirm_delete_item_msg: 'Are you sure you want to delete this item?',
        delete_item: 'Delete Item',
        back: 'Back'
    },
    report: {
        revenue: 'Total Revenue',
        avg_bill: 'Avg Bill Value',
        orders: 'Total Orders',
        by_item: 'Sales by Item',
        quantity: 'Qty Sold',
        sales_report: 'Sales Report',
        total_revenue: 'TOTAL REVENUE',
        total_orders: 'TOTAL ORDERS',
        product_count: 'PRODUCTS (QTY)',
        topping_count: 'TOPPINGS',
        cash_label: 'Cash:',
        transfer_label: 'Transfer:',
        daily_report: 'END OF DAY REPORT',
        summary: 'SUMMARY',
        goods: 'GOODS',
        cost_price: 'Cost:',
        sold_goods: 'GOODS SOLD',
        total: 'Total'
    },
    auth: {
        login: 'Login',
        logout: 'Logout',
        end_session: 'End Session',
        username: 'Username',
        password: 'Password',
        placeholder_user: 'Enter username...',
        placeholder_pass: 'Enter password...',
        logout_confirm: 'Are you sure you want to end your session?',
        role_admin: 'Store Manager',
        role_staff: 'Cashier',
        invalid_creds: 'Invalid username or password.',
        register_success: 'Registration successful! Please check your email to verify your account.',
        pass_mismatch: 'Passwords do not match',
        register_title: 'Create Account',
        register_subtitle: 'Register your shop and start managing',
        shop_info: 'Shop Information',
        admin_account: 'Admin Account',
        have_account: 'Already have an account?',
        confirm_password: 'Confirm Password'
    },
    register: {
        shop_code: 'Shop Code',
        shop_name: 'Shop Name',
        address: 'Address',
        phone: 'Phone Number',
        email: 'Shop Email',
        tax_code: 'Tax Code',
        plan: 'Subscription Plan',
        enter_shop_code: 'Enter shop code',
        enter_shop_name: 'Enter shop name',
        enter_address: 'Enter address',
        enter_phone: 'Enter phone',
        enter_email: 'Enter shop email',
        enter_tax: 'Enter tax code',
        enter_username: 'Enter username',
        register_btn: 'Register'
    },

    common: {
        loading: 'Loading...',
        loading_data: 'Loading data...',
        processing: 'Processing...',
        error: 'An error occurred',
        no_data: 'No data found',
        search: 'Search...',
        all: 'All',
        table: 'Table',
        status: 'Status',
        action: 'Actions',
        note: 'Note',
        payment_method: 'Payment Method',
        update_payment: 'Update Payment',
        cash: 'Cash',
        transfer: 'Transfer',
        mixed: 'Mixed',
        update: 'Update',
        save_changes: 'Save Changes',
        create: 'Create',
        receipt_title: 'Sales Receipt',
        code: 'Code',
        time: 'Time',
        type: 'Type',
        items_list: 'Items List',
        subtotal: 'Subtotal',
        discount: 'Discount',
        grand_total: 'Grand Total',
        payment: 'Payment',
        order_detail: 'Order Detail',
        order_history: 'Order History',
        no_orders_today: 'No orders found today.',
        guest: 'Guest',
        pay: 'Pay',
        payment_success: 'Payment Successful',
        payment_success_msg: 'Order received! Syncing...',
        agree: 'Agree',
        diff: 'Diff',
        required_error: 'Name and Category are required',
        revenue_trend: 'Revenue Trend',
        top_products: 'Top 10 Products',
        by_payment_method: 'By Payment Method',
        table_name: 'Table {name}',
        item_count: '{count} ITEMS',
        search_placeholder: 'Search by name, code...',
        all_categories: 'All Categories',
        developed_by: 'Developed by',
        version: 'Version',
        role: 'Role',
        order_count: 'orders',
        dark_mode: 'Dark Mode',
        pick_date: 'Select Date',
        cost: 'Cost',
        added_item: '{name} added',
        amount_money: 'Amount',
        percent: 'Percentage',
        change_customer: 'Change Customer',
        no_products_found: 'No products found',
        no_products_category: 'No products available',
        try_another_search: 'Try another keyword or category',
        update_success_msg: 'Updated {name}',
        add_to_table_success: '{name} added to Table {table}',
        add_to_cart_success: 'Added to cart',
        subtitle: 'Order Management System',
        print_bill: 'Print Bill',
        print_confirm_title: 'Confirm Print',
        print_confirm_msg: 'Do you want to print the bill for table {name}?',
        select_print_lang: 'Select print language',
        vi_lang: 'Vietnamese',
        en_lang: 'English',
        print: 'Print',
        unit_price: 'Price',
        item_total: 'Total'
    },
    modal: {
        create_product: 'Create Product',
        edit_product: 'Edit Product',
        create_user: 'Create User',
        delete_order_confirm: 'Are you sure you want to delete this order?',
        delete_order_success: 'Order deleted successfully',
        delete_order_error: 'Failed to delete order',
        save_error: 'Failed to save',
        update_success: 'Updated successfully',
        create_success: 'Created successfully',
        add_success: 'Added successfully',
        load_error: 'Failed to load data',
        action_failed: 'Action failed',
        sync_success: 'Menu synced successfully!',
        sync_all_success: 'Data synced (Menu, Orders, Reports)!',
        sync_error: 'Sync error',
        confirm_status_title: 'Confirm Status Change',
        confirm_status_msg: 'Are you sure you want to change the status of {name}?',
        confirm_enable: 'Enable Now',
        confirm_disable: 'Disable',
        status_active_alert: 'Activated {name}',
        status_inactive_alert: 'Deactivated {name}',
        no_result: 'No results found',
        no_match: 'No matching data found',
        clear_search: 'Clear Search',
        permission_denied: 'Permission denied',
        confirm_delete_order_title: 'Delete Order',
        confirm_delete_order_msg: 'Are you sure you want to delete order #{id}? This will mark the order as removed but will not delete data.',
        confirm_delete_btn: 'Confirm Delete',
        no_orders_found: 'No orders found',
        view_edit: 'View/Edit',
        load_orders_error: 'Failed to load orders',
        export_loading: 'Generating report...',
        export_error: 'Failed to export report',
        total_items: 'Total Items'
    },
    form: {
        order_status: 'Order Status',
        order_note: 'Order Note',
        note_placeholder: 'Note for the entire order...',
        item_list: 'Item List',
        customer_at: 'Customer at',
        total_amount: 'Total Amount',
        product_name: 'Product Name',
        product_code: 'Product Code',
        category: 'Category',
        price: 'Price',
        cost: 'Cost',
        image_url: 'Image URL',
        is_active: 'Is Active',
        is_topping: 'Is Topping',
        toppings_list: 'Toppings List',
        empty_toppings: 'No toppings available',
        new_password: 'New Password (Leave blank to keep)',
        role: 'Role',
        active: 'Active',
        enable: 'Enable',
        locked: 'Locked'
    },
    settings: {
        shop_settings: 'Shop Settings',
        shop_settings_desc: 'Manage your shop information and tax configurations',
        general_info: 'General Information',
        tax_fees: 'Tax & Fees',
        tax_fees_desc: 'These rates will be applied to all future orders automatically.',
        logo_url: 'Logo URL',
        vat_rate: 'VAT Rate (%)',
        surcharge_rate: 'Surcharge Rate (%)',
        service_charge: 'Service Charge (%)'
    },
    dashboard: {
        revenue_7_days: 'Revenue last 7 days',
        recent_orders: 'Recent Orders',
        no_orders: 'No orders yet',
        title: 'Dashboard'
    }
}
