export const vi = {
    nav: {
        overview: 'Tổng quan kinh doanh',
        invoices: 'Lịch sử hóa đơn',
        menu: 'Danh mục thực đơn',
        hr: 'Quản trị nhân sự',
        floorplan: 'Sơ đồ bàn',
        shift_report: 'Báo cáo ca',
        reports: 'Báo cáo doanh thu',
        orders: 'Quản lý đơn',
        products: 'Quản lý sản phẩm',
        users: 'Quản lý nhân viên',
        home: 'Trang chủ',
        dashboard: 'Báo cáo',
        product_qty: 'Sản phẩm (Ly)',
        topping: 'Topping',
        history: 'Lịch sử',
        language: 'Ngôn ngữ'
    },
    app: {
        exit_title: 'Thoát ứng dụng',
        exit_confirm: 'Bạn có chắc chắn muốn thoát?',
        exit_ok: 'Thoát',
        exit_cancel: 'Hủy',
        admin_subtitle: 'Cổng quản trị viên'
    },
    action: {
        checkout: 'Thanh toán',
        add_item: 'Thêm món',
        edit: 'Chỉnh sửa',
        delete: 'Xóa',
        sync: 'Đồng bộ Cloud',
        save: 'Lưu',
        cancel: 'Hủy',
        confirm: 'Xác nhận',
        refresh: 'Làm mới',
        export: 'Xuất báo cáo',
        add_new: 'Thêm mới',
        update: 'Cập nhật'
    },
    status: {
        active: 'Đang phục vụ',
        empty: 'Bàn trống',
        paid: 'Đã hoàn thành',
        pending: 'Đang chờ',
        removed: 'Đã xóa',
        draft: 'Bản nháp',
        occupied: 'Có khách'
    },
    pos: {
        takeaway: 'Mang về',
        placeholder_note: 'Ví dụ: ít đường, không đá...',
        add_to_order: 'Thêm vào đơn',
        update_item: 'Cập nhật món',
        qty: 'Số lượng'
    },
    cart: {
        empty_title: 'Chưa có món nào',
        empty_instruction_prefix: 'Vui lòng nhấn nút',
        empty_instruction_suffix: 'để thêm món mới vào đơn hàng',
        save_draft: 'Lưu nháp',
        item_note_title: 'Ghi chú món',
        order_note_title: 'Ghi chú đơn hàng',
        enter_note_placeholder: 'Nhập ghi chú...',
        confirm_delete_item_title: 'Xác nhận xóa',
        confirm_delete_item_msg: 'Bạn có chắc chắn muốn xóa món này?',
        delete_item: 'Xóa món',
        back: 'Quay lại'
    },
    report: {
        revenue: 'Tổng doanh thu',
        avg_bill: 'Giá trị TB/Đơn',
        orders: 'Tổng đơn hàng',
        by_item: 'Doanh thu theo món',
        quantity: 'SL bán',
        sales_report: 'Báo cáo kinh doanh',
        total_revenue: 'TỔNG DOANH THU',
        total_orders: 'TỔNG SỐ ĐƠN HÀNG',
        product_count: 'SẢN PHẨM (LY)',
        topping_count: 'TOPPING',
        cash_label: 'Tiền mặt:',
        transfer_label: 'Chuyển khoản:',
        daily_report: 'BÁO CÁO CUỐI NGÀY',
        summary: 'TỔNG HỢP',
        goods: 'HÀNG HÓA',
        cost_price: 'Giá vốn:',
        sold_goods: 'HÀNG HÓA BÁN RA',
        total: 'Tổng'
    },
    auth: {
        login: 'Đăng nhập',
        logout: 'Đăng xuất',
        end_session: 'Kết thúc phiên làm việc',
        username: 'Tên đăng nhập',
        password: 'Mật khẩu',
        placeholder_user: 'Nhập username...',
        placeholder_pass: 'Nhập password...',
        logout_confirm: 'Bạn có chắc chắn muốn kết thúc phiên làm việc?',
        role_admin: 'Quản lý',
        role_staff: 'Nhân viên',
        invalid_creds: 'Sai tài khoản hoặc mật khẩu.'
    },
    common: {
        loading: 'Đang tải dữ liệu...',
        processing: 'Đang xử lý...',
        error: 'Đã có lỗi xảy ra',
        no_data: 'Không tìm thấy dữ liệu',
        search: 'Tìm kiếm...',
        all: 'Tất cả',
        table: 'Bàn',
        status: 'Trạng thái',
        action: 'Thao tác',
        note: 'Ghi chú',
        payment_method: 'Phương thức thanh toán',
        cash: 'Tiền mặt',
        transfer: 'Chuyển khoản',
        mixed: 'Hỗn hợp',
        update: 'Cập nhật',
        create: 'Tạo mới',
        receipt_title: 'Hóa đơn bán hàng',
        code: 'Mã đơn',
        time: 'Thời gian',
        type: 'Hình thức',
        items_list: 'Danh sách món',
        subtotal: 'Tạm tính',
        discount: 'Giảm giá',
        grand_total: 'Tổng cộng',
        payment: 'Thanh toán',
        order_detail: 'Chi tiết đơn hàng',
        order_history: 'Lịch sử đơn hàng',
        no_orders_today: 'Chưa có đơn hàng nào hôm nay.',
        guest: 'Khách lẻ',
        pay: 'Thanh toán',
        payment_success: 'Thành công',
        payment_success_msg: 'Đã nhận đơn hàng! Đang đồng bộ...',
        agree: 'Đồng ý',
        diff: 'Lệch',
        required_error: 'Tên và Danh mục là bắt buộc',
        revenue_trend: 'Xu hướng doanh thu',
        top_products: 'Top 10 Sản phẩm',
        by_payment_method: 'Phương thức thanh toán',
        table_name: 'Bàn {name}',
        item_count: '{count} MÓN',
        search_placeholder: 'Tìm theo tên, mã món...',
        all_categories: 'Tất cả danh mục',
        developed_by: 'Phát triển bởi',
        version: 'Phiên bản',
        role: 'Vai trò',
        order_count: 'đơn hàng',
        dark_mode: 'Chế độ tối',
        pick_date: 'Chọn ngày',
        cost: 'Giá vốn',
        added_item: '{name} đã được thêm',
        amount_money: 'Số tiền',
        percent: 'Phần trăm',
        change_customer: 'Thay đổi khách hàng',
        no_products_found: 'Không tìm thấy sản phẩm',
        no_products_category: 'Chưa có sản phẩm nào',
        try_another_search: 'Thử từ khóa hoặc danh mục khác',
        update_success_msg: 'Đã cập nhật {name}',
        add_to_table_success: '{name} đã thêm vào Bàn {table}',
        add_to_cart_success: '{name} đã thêm vào giỏ',
        subtitle: 'Phần mềm Order',
        topping: 'Topping',
        toping: 'Topping'
    },
    modal: {
        edit_product: 'Chỉnh sửa mặt hàng',
        create_product: 'Thêm mặt hàng mới',
        edit_user: 'Chỉnh sửa nhân viên',
        create_user: 'Thêm nhân viên mới',
        delete_order_confirm: 'Bạn có chắc chắn muốn xóa đơn hàng này không?',
        delete_order_success: 'Đã xóa đơn hàng thành công',
        delete_order_error: 'Lỗi khi xóa đơn hàng',
        save_error: 'Lỗi khi lưu',
        update_success: 'Cập nhật thành công',
        create_success: 'Tạo thành công',
        add_success: 'Đã thêm thành công',
        load_error: 'Không thể tải dữ liệu',
        action_failed: 'Thao tác thất bại',
        sync_success: 'Đã đồng bộ thực đơn mới!',
        sync_error: 'Lỗi đồng bộ',
        confirm_status_title: 'Xác nhận thay đổi trạng thái',
        confirm_status_msg: 'Bạn có chắc chắn muốn thay đổi trạng thái của {name} không?',
        confirm_enable: 'Kích hoạt ngay',
        confirm_disable: 'Ngưng hoạt động',
        status_active_alert: 'Đã kích hoạt {name}',
        status_inactive_alert: 'Đã ngưng {name}',
        no_result: 'Không tìm thấy kết quả',
        no_match: 'Không có dữ liệu phù hợp',
        clear_search: 'Xóa tìm kiếm',
        permission_denied: 'Bạn không có quyền truy cập',
        confirm_delete_order_title: 'Xóa đơn hàng',
        confirm_delete_order_msg: 'Bạn có chắc chắn muốn xóa đơn hàng #{id} không? Thao tác này sẽ đánh dấu đơn hàng là đã xóa nhưng không mất dữ liệu.',
        confirm_delete_btn: 'Xác nhận xóa',
        no_orders_found: 'Không tìm thấy đơn hàng nào',
        view_edit: 'Xem/Sửa',
        load_orders_error: 'Không thể tải danh sách đơn hàng',
        export_loading: 'Đang tạo báo cáo...',
        export_error: 'Lỗi khi xuất báo cáo',
        total_items: 'Tổng số mặt hàng'
    },
    form: {
        order_status: 'Trạng thái đơn hàng',
        order_note: 'Ghi chú đơn hàng',
        note_placeholder: 'Ghi chú cho cả đơn hàng...',
        item_list: 'Danh sách món',
        customer_at: 'Khách lúc',
        total_amount: 'Tổng tiền',
        product_name: 'Tên món',
        product_code: 'Mã món',
        category: 'Danh mục',
        price: 'Giá bán (đ)',
        cost: 'Giá vốn (đ)',
        image_url: 'URL Hình ảnh',
        is_active: 'Đang kinh doanh',
        is_topping: 'Đây là Topping',
        toppings_list: 'Topping đi kèm',
        empty_toppings: 'Chưa có topping nào trong thực đơn.',
        new_password: 'Mật khẩu mới (Để trống nếu không đổi)',
        role: 'Vai trò',
        active: 'Hoạt động',
        enable: 'Kích hoạt',
        locked: 'Đã khóa'
    }
}
