using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text;
using TheCoffeeCream.Application.Interfaces;
using TheCoffeeCream.Domain.Entities;

namespace TheCoffeeCream.Api.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    [Authorize(Roles = "Admin")] // Only Shop Admins or Super Admins
    public class MenuImportExportController : ControllerBase
    {
        private readonly IProductRepository _productRepository;
        private readonly IUserRepository _userRepository;

        public MenuImportExportController(IProductRepository productRepository, IUserRepository userRepository)
        {
            _productRepository = productRepository;
            _userRepository = userRepository;
        }

        [HttpGet("export")]
        public async Task<IActionResult> ExportMenu()
        {
            var userId = User.FindFirst("id")?.Value ?? User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (string.IsNullOrEmpty(userId)) return Unauthorized();

            var user = await _userRepository.GetByIdAsync(userId);
            if (user == null || string.IsNullOrEmpty(user.ShopId)) return NotFound("Shop not found.");

            var products = await _productRepository.GetAllAsync(user.ShopId);
            // Ensure we load categories if not already loaded (repository includes them)
            
            var csv = new StringBuilder();
            csv.AppendLine("CategoryName,ProductCode,ProductName,Price,Cost,IsActive,IsTopping");

            foreach (var p in products)
            {
                var categoryName = p.Category?.Name ?? "";
                // Escape commas in names
                var line = $"{EscapeCsv(categoryName)},{EscapeCsv(p.Code)},{EscapeCsv(p.Name)},{p.Price},{p.Cost},{p.IsActive},{p.IsTopping}";
                csv.AppendLine(line);
            }

            return File(Encoding.UTF8.GetBytes(csv.ToString()), "text/csv", "menu_export.csv");
        }

        [HttpPost("import")]
        public async Task<IActionResult> ImportMenu(IFormFile file)
        {
            var userId = User.FindFirst("id")?.Value ?? User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (string.IsNullOrEmpty(userId)) return Unauthorized();

            var user = await _userRepository.GetByIdAsync(userId);
            if (user == null || string.IsNullOrEmpty(user.ShopId)) return NotFound("Shop not found.");

            if (file == null || file.Length == 0) return BadRequest("No file uploaded.");

            int successCount = 0;
            int errorCount = 0;
            var errors = new List<string>();

            using (var reader = new StreamReader(file.OpenReadStream()))
            {
                // Skip header
                var header = await reader.ReadLineAsync();
                
                while (!reader.EndOfStream)
                {
                    var line = await reader.ReadLineAsync();
                    if (string.IsNullOrWhiteSpace(line)) continue;

                    try
                    {
                        var values = ParseCsvLine(line);
                        // Expected: CategoryName,ProductCode,ProductName,Price,Cost,IsActive,IsTopping
                        if (values.Length < 3) 
                        {
                            errorCount++; 
                            continue; 
                        }

                        string categoryName = values[0].Trim();
                        string code = values[1].Trim();
                        string name = values[2].Trim();
                        decimal price = decimal.Parse(values[3]);
                        decimal cost = values.Length > 4 ? decimal.Parse(values[4]) : 0;
                        bool isActive = values.Length > 5 && bool.Parse(values[5]);
                        bool isTopping = values.Length > 6 && bool.Parse(values[6]);

                        // 1. Find or Create Category
                        var categories = await _productRepository.GetCategoriesAsync(user.ShopId);
                        var category = categories.FirstOrDefault(c => c.Name.Equals(categoryName, StringComparison.OrdinalIgnoreCase));

                        if (category == null)
                        {
                            category = new Category
                            {
                                ShopId = user.ShopId,
                                Name = categoryName,
                                IsActive = true,
                                Rank = categories.Count() + 1
                            };
                            await _productRepository.CreateCategoryAsync(category);
                            // Refresh list or just reuse this obj. 
                            // Note: We might need the ID generated by DB if not GUID. But Entities use GUID usually.
                            // Let's assume Entity Framework sets the ID on the object.
                        }

                        // 2. Find or Create/Update Product
                        // Check if product exists by Code (if provided) or Name within Category?
                        // Let's use Code as unique identifier if present, else Name.
                        var products = await _productRepository.GetAllAsync(user.ShopId);
                        Product? existingProduct = null;

                        if (!string.IsNullOrEmpty(code))
                        {
                            existingProduct = products.FirstOrDefault(p => p.Code == code);
                        }
                        
                        // If no code, or not found by code, try name match in that category
                        if (existingProduct == null)
                        {
                             existingProduct = products.FirstOrDefault(p => p.Name.Equals(name, StringComparison.OrdinalIgnoreCase) && p.CategoryId == category.Id);
                        }

                        if (existingProduct != null)
                        {
                            // Update
                            existingProduct.Name = name;
                            existingProduct.Price = price;
                            existingProduct.Cost = cost;
                            existingProduct.IsActive = isActive;
                            existingProduct.IsTopping = isTopping;
                            existingProduct.CategoryId = category.Id;
                            // Code? If we matched by Name, we might update Code.
                            if (!string.IsNullOrEmpty(code)) existingProduct.Code = code;

                            await _productRepository.UpdateAsync(existingProduct);
                        }
                        else
                        {
                            // Create
                            var newProduct = new Product(
                                Guid.NewGuid(),
                                name,
                                price,
                                isTopping,
                                category.Id,
                                category,
                                code,
                                cost,
                                "",
                                isActive
                            );
                            newProduct.ShopId = user.ShopId;
                            await _productRepository.CreateAsync(newProduct);
                        }
                        successCount++;
                    }
                    catch (Exception ex)
                    {
                        errorCount++;
                        errors.Add($"Error processing line '{line}': {ex.Message}");
                    }
                }
            }

            return Ok(new { 
                Message = $"Import completed. Success: {successCount}, Errors: {errorCount}", 
                Errors = errors 
            });
        }

        private string EscapeCsv(string field)
        {
            if (string.IsNullOrEmpty(field)) return "";
            if (field.Contains(",") || field.Contains("\"") || field.Contains("\n"))
            {
                return $"\"{field.Replace("\"", "\"\"")}\"";
            }
            return field;
        }

        private string[] ParseCsvLine(string line)
        {
            // Simple split for now, robust CSV parsing is complex.
            // Assuming simple structure without commas in values for this MVP or handled by quotes.
            // But we should handle quotes if possible.
            // Let's use a basic regex or split if we assume no commas in names for simplicity first user request.
            // User asked for "simple structure".
            // Let's try to support quoted strings.
            var result = new List<string>();
            bool inQuotes = false;
            var currentField = new StringBuilder();

            for (int i = 0; i < line.Length; i++)
            {
                char c = line[i];
                if (c == '\"')
                {
                    inQuotes = !inQuotes;
                }
                else if (c == ',' && !inQuotes)
                {
                    result.Add(currentField.ToString());
                    currentField.Clear();
                }
                else
                {
                    currentField.Append(c);
                }
            }
            result.Add(currentField.ToString());
            return result.ToArray();
        }
    }
}
