services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TheCoffeeCream;User Id=sa;Password=YourStrong(!)Password;TrustServerCertificate=True
    networks:
      - coffee-net
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong(!)Password
    ports:
      - "1433:1433"
    networks:
      - coffee-net
    volumes:
      - mssql_data:/var/opt/mssql

  app-admin:
    build:
      context: ./mobile
      dockerfile: apps/app-admin/Dockerfile
    ports:
      - "4000:80"
    networks:
      - coffee-net
    depends_on:
      - api

  app-staff:
    build:
      context: ./mobile
      dockerfile: apps/app-staff/Dockerfile
    ports:
      - "4001:80"
    networks:
      - coffee-net
    depends_on:
      - api

  app-owner:
    build:
      context: ./mobile
      dockerfile: apps/app-owner/Dockerfile
    ports:
      - "4002:80"
    networks:
      - coffee-net
    depends_on:
      - api

networks:
  coffee-net:
    driver: bridge

volumes:
  mssql_data:
